sequenceDiagram
    actor User
    participant Booking

    User->>Booking: leave_review(booking, rating, comment)
    alt Booking Ended
        create participant Review
        Booking->>Review: create_review(booking, rating, comment)
        Review-->>User:Review created
    else Booking not ended
        Booking-->>User: Can't post review for this booking
    end
